[toolchain]
anchor_version = "0.31.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
opentela_rewards = "HMSLAjUbu7XkMmw74fmTMoksg2TSaatDYZ8VjQUU4HdE"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npm test"
